### ISSUE TITLE
A moving body sinks into a complex board body that is created with "threeToCannon.Type.MESH"

### ISSUE THREAD

**Issue by samedbayrakoglu** [donmccurdy/three-to-cannon#29]
thanks for this awesome library.

I'm having a problem that a moving body reaches out into a complex board body that is created with "threeToCannon.Type.MESH", as can be seen at the bottom. This issue has been discussed in Q&A's but never been solved. Is there a chance to solve it?

thanks in advance...

![movePillow](https://user-images.githubusercontent.com/62354588/98131979-ed665380-1ecc-11eb-89c0-8960de9aa514.gif)

**Comment by donmccurdy** [comment]
This is more likely an issue for the aframe-physics-system repository, but also note the collision matrix here, if you're using its CannonJS mode:

https://github.com/schteppe/cannon.js#features

Many shapes cannot collide correctly with the 'mesh' type, so it's usually best to use one or more primitive shapes instead of 'mesh'.
