### ISSUE TITLE
What is the file that I have to import? 

### ISSUE THREAD

**Issue by alon2138** [donmccurdy/three-to-cannon#63]
Hello, sorry for this newbie question, but, after installing the library I try to import it in my client.js (im using express and made sure that three-to-cannon folder was being served) as you showed in the readme.md and it gives me a 404 error not found, so, what is the file that I have to export exactly? Because apparently thats the only way imports work in my app.

**Comment by donmccurdy** [comment]
Hi – The only official distributable of this library is the NPM package, [`three-to-cannon`](https://www.npmjs.com/package/three-to-cannon). I recommend installing from NPM, rather than cloning the repository.  If you'd prefer to do without NPM entirely, NPM packages get re-hosted by CDNs like [Unpkg](https://unpkg.com/three-to-cannon@4.0.2/dist/three-to-cannon.js). and you can download the compiled files from there:

- CommonJS: [three-to-cannon.js](https://unpkg.com/three-to-cannon@4.0.2/dist/three-to-cannon.js)
- ES Module: [three-to-cannon.modern.js](https://unpkg.com/three-to-cannon@4.0.2/dist/three-to-cannon.modern.js)

Both files can also be compiled from source with `npm install && npm run dist`.

Note that both files have peer dependencies on the `three` and `cannon-es` modules, which either need to be installed with NPM or have their import/require paths replaced in the first lines of the code.

**Comment by alon2138** [comment]
Sorry to answer almost a month after, but I have been busy trying to find a way to make the plane in the video a Cannon body that didn't require three-to-cannon because I am not able to import it. I tried with a custom heightfield, but before getting into that loop and math mess, I have to try implementing three-to-cannon once again, as I see it as the perfect solution even though I can't import it. So here I am. Thanks for your attention.

https://user-images.githubusercontent.com/50425695/147248772-c170923f-d2d9-4c80-ad4a-ccef9c6f0133.mp4

**Comment by donmccurdy** [comment]
The correct way to install this is with the NPM package, as [documented in the readme](https://github.com/donmccurdy/three-to-cannon#api). If you're copy/pasting files or using a CDN I'm afraid I can't provide support on getting that to work with your build system. Using a CDN is more complicated for libraries with peer dependencies, which this project needs (three.js and cannon.js).
